// Copyright (c) 2017 Northwestern Mutual.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// This file was automatically generated by lister-gen

package v2

import (
	v2 "github.com/northwesternmutual/kanali/pkg/apis/kanali.io/v2"
	"k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ApiKeyLister helps list ApiKeies.
type ApiKeyLister interface {
	// List lists all ApiKeies in the indexer.
	List(selector labels.Selector) (ret []*v2.ApiKey, err error)
	// Get retrieves the ApiKey from the index for a given name.
	Get(name string) (*v2.ApiKey, error)
	ApiKeyListerExpansion
}

// apiKeyLister implements the ApiKeyLister interface.
type apiKeyLister struct {
	indexer cache.Indexer
}

// NewApiKeyLister returns a new ApiKeyLister.
func NewApiKeyLister(indexer cache.Indexer) ApiKeyLister {
	return &apiKeyLister{indexer: indexer}
}

// List lists all ApiKeies in the indexer.
func (s *apiKeyLister) List(selector labels.Selector) (ret []*v2.ApiKey, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2.ApiKey))
	})
	return ret, err
}

// Get retrieves the ApiKey from the index for a given name.
func (s *apiKeyLister) Get(name string) (*v2.ApiKey, error) {
	key := &v2.ApiKey{ObjectMeta: v1.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2.Resource("apikey"), name)
	}
	return obj.(*v2.ApiKey), nil
}
