---

kind: ConfigMap
apiVersion: v1
metadata:
  name: kanali-validator-config
  namespace: {{default "default" .Values.kanali.validator.namespace}}
data:
  config.toml: |-
    [process]
    log_level = {{default "info" .Values.kanali.logLevel  | quote}}

    [profiling]
    insecure_port = {{.Values.kanali.gateway.profiler.insecurePort}}
    insecure_bind_address = "{{.Values.kanali.gateway.profiler.insecureBindAddress}}"

    [prometheus]
    insecure_port = {{default 0 .Values.kanali.gateway.prometheus.insecurePort}}
    insecure_bind_address = "{{default "0.0.0.0" .Values.kanali.gateway.prometheus.insecureBindAddress}}"
    secure_port = {{default 0 .Values.kanali.gateway.prometheus.securePort}}
    secure_bind_address = "{{default "0.0.0.0" .Values.kanali.gateway.prometheus.secureBindAddress}}"

    [server]
    insecure_port = {{default 0 .Values.kanali.gateway.insecurePort}}
    insecure_bind_address = "{{default "0.0.0.0" .Values.kanali.gateway.insecureBindAddress}}"
    secure_port = {{default 0 .Values.kanali.gateway.securePort}}
    secure_bind_address = "{{default "0.0.0.0" .Values.kanali.gateway.secureBindAddress}}"

    {{- if .Values.kanali.gateway.securePort }}
    [server.tls]
    cert_file = "/etc/pki/tls.crt"
    key_file = "/etc/pki/tls.key"
    {{- if .Values.kanali.gateway.tls.verifyClient }}
    ca_file = "/etc/pki/tls.ca"
    {{- end }}
    {{- end }}