---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanali-validator
  namespace: {{default "default" .Values.validator.namespace}}
spec:
  selector:
    matchLabels:
      app: kanali-validator
  template:
    metadata:
      labels:
        app: kanali-validator
    spec:
      serviceAccountName: kanali-validator
      containers:
      - name: validator
        imagePullPolicy: {{default "IfNotPresent" .Values.validator.image.pullPolicy}}
        image: {{.Values.validator.image.name}}:{{default "latest" .Values.validator.image.tag}}
        command:
        - /validator
        - start
        ports:
        - name: validator
          containerPort: {{.Values.validator.securePort}}
        - name: prometheus
          containerPort: {{.Values.validator.prometheus.insecurePort}}
        - name: profiler
          containerPort: {{.Values.validator.profiler.insecurePort}}
        readinessProbe:
          tcpSocket:
            port: {{.Values.validator.securePort}}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{.Values.validator.securePort}}
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: pki
          mountPath: /etc/pki
          readOnly: true
        - name: config
          mountPath: /etc/validator
      volumes:
      - name: pki
        projected:
          sources:
          - secret:
              name: {{default "kanali-pki" .Values.validator.tls.secretName}}
              items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
              {{- if .Values.validator.tls.verifyClient }}
              - key: tls.ca
                path: tls.ca
              {{- end }}
      - name: config
        projected:
          sources:
          - configMap:
              name: kanali-validator-config