---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kanali-validator
  namespace: {{default "default" .Values.validator.namespace}}
spec:
  maxReplicas: {{.Values.validator.scale.maxReplicas}}
  minReplicas: {{.Values.validator.scale.minReplicas}}
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: kanali-validator
  targetCPUUtilizationPercentage: {{.Values.validator.scale.targetCPU}}