---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kanali
  namespace: {{default "default" .Values.kanali.namespace}}
spec:
  maxReplicas: {{.Values.kanali.gateway.scale.maxReplicas}}
  minReplicas: {{.Values.kanali.gateway.scale.minReplicas}}
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: kanali
  targetCPUUtilizationPercentage: {{.Values.kanali.gateway.scale.targetCPU}}