---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kanali
rules:
- apiGroups: ["kanali.io"]
  resources: ["*"]
  verbs: ["watch", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["services", "secrets"]
  verbs: ["watch", "list", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kanali
  labels:
    app: kanali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kanali
subjects:
- kind: ServiceAccount
  name: kanali
  namespace: {{default "default" .Values.kanali.namespace}}


---
apiVersion: kanali.io/v2
kind: ApiProxy
metadata:
  name: example
spec:
  source:
    path: /foo
  target:
    path: /
    backend:
      endpoint: https://foo.bar.com:8443

---
apiVersion: kanali.io/v2
kind: ApiProxy
metadata:
  name: foo
spec:
  source:
    path: /foo
  target:
    path: /
    backend:
      endpoint: https://foo.bar.com:8443