---

apiVersion: v1
kind: Service
metadata:
  name: kanali-validator
  namespace: {{default "default" .Values.kanali.validator.namespace}}
  {{- if .Values.tags.metrics }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '{{.Values.kanali.validator.prometheus.insecurePort}}'
  {{- end }}
spec:
  selector:
    app: kanali-validator
  ports:
  {{- if .Values.kanali.validator.securePort }}
  - name: https
    port: {{.Values.kanali.validator.securePort}}
  {{- end }}
  type: ClusterIP