---

apiVersion: v1
kind: Service
metadata:
  name: kanali-validator-profiler
  namespace: {{default "default" .Values.kanali.validator.namespace}}
spec:
  selector:
    app: kanali-validator
  ports:
  - name: profiler
    port: {{.Values.kanali.validator.profiler.insecurePort}}
  type: NodePort