---

apiVersion: v1
kind: Service
metadata:
  name: kanali-validator
  namespace: {{default "default" .Values.validator.namespace}}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '{{.Values.validator.prometheus.insecurePort}}'
spec:
  selector:
    app: kanali-validator
  ports:
  {{- if .Values.validator.securePort }}
  - name: https
    port: {{.Values.validator.securePort}}
  {{- end }}
  type: ClusterIP