---

apiVersion: v1
kind: Service
metadata:
  name: kanali-profiler
  namespace: {{default "default" .Values.namespace}}
spec:
  selector:
    app: kanali
  ports:
  - name: profiler
    port: {{.Values.gateway.profiler.insecurePort}}
  type: NodePort