---

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kanali-validator
webhooks:
- name: validator.kanali.io
  clientConfig:
    service:
      namespace: {{default "default" .Values.kanali.validator.namespace}}
      name: kanali-validator
      path: /
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEQ2pDQ0FmS2dBd0lCQWdJSkFJcE1jUEZHT0MzN01BMEdDU3FHU0liM0RRRUJDd1VBTUNFeEh6QWRCZ05WDQpCQU1NRm50N0lHTmxjblJwWm1sallYUmxMbTVoYldVZ2ZYMHdIaGNOTVRnd05ERXdNakV6TWpVd1doY05NVGt3DQpOREV3TWpFek1qVXdXakFoTVI4d0hRWURWUVFEREJaN2V5QmpaWEowYVdacFkyRjBaUzV1WVcxbElIMTlNSUlCDQpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeDU4Zjg3czViK1A0ZGJOd3dVeXowWG5xDQplbE5IcGRQbE1NcjR0VTl2aEZuYW9UUGQzZyt3RmlCVjFrNjFiZzN3MHRDUS9QR01OWlZVZWpPOFVHV1dqcllHDQpHUy9Fd0NQQU5hN0Y0OGNqZ2ZveDlPa3ArRWo1TGthVUdNWUE2OUhxNXJ6Z3ExNmR0S2w0K290ZG5aUmkzMmlnDQp2b1FBYTIxcWZlR2haUnMwZDhabXRsdUoydWtQQTM3bHF4c3owd0lmWk5YdGxFcFM1dEpWcUVoRW5ERys2THM5DQpiTGZ0dDgybjJNcXJVcWtUT2JNdlZMNUJDR08rUTBaNXQreTErd2FwcjJIckk2c0lMSEVVdE9UOW8wVHhiZDY0DQpqRVpVSHE3VDVJVituMGFzdS95YnFiVEFhdEhINEFZTnQ1blZvMkdtR0VoTVpRNk9HMkxLbVhhVC9xMTRqUUlEDQpBUUFCbzBVd1F6QkJCZ05WSFJFRU9qQTRnaHdxTG1SbFptRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d1DQpnZ2txTG1SbFptRjFiSFNDRFNvdVpHVm1ZWFZzZEM1emRtTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRENwDQpPa1dhNnFGK3RQYVJ0c0R3WExVcmhSY2FTZk1CZ1ByNW1EeTBlTVZtbmNDbGRvYkgrVjlGTzd5SGVBUjU2L2NhDQpPcVdHaFVKVGhVT3Nkc09PUEFaaWthOHp5c0hCY3Y3U3pQczlWKzdvdHJQR0JmbHRYbWVMRmxKeVUzR3MzUHVXDQphN1pOSW1pSDM2STF2VEhwc09pdURMYWV0VnIwdHBlZFlmcE5jczdEZkIzVGpiU2llRS96MmVETEdSWU9YTCtzDQpXK1RrUWpMZTBDQ25OL3NqWG80M2xpVmZlVzhMbzhydjg3UGxqNSs0ajNnR21jT0ZSZ1dhQWVxMHNWRlF0OXRsDQoraGhyakZXdFdVVENtbm05dlFmS0Nqb3JzMHZ0M0lRdDlUVU1WWjlIK1NRNTcrZEpMakFhRVpxRmVtQ2NPSldVDQo3KzRzOTlJZnFRdUczaW5QbjJjPQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["kanali.io"]
    apiVersions: ["v2"]
    resources: ["*"]
  failurePolicy: "Fail"