---

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kanali-validator
webhooks:
- name: kanali-validator
  clientConfig:
    service:
      namespace: {{default "default" .Values.kanali.validator.namespace}}
      name: kanali-validator
      path: /
    caBundle: ""
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["kanali.io"]
    apiVersions: ["v2"]
    resources: ["*"]
  failurePolicy: "Fail"