// Copyright (c) 2017 Northwestern Mutual.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// This file was automatically generated by informer-gen

package v2

import (
	internalinterfaces "github.com/northwesternmutual/kanali/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ApiKeies returns a ApiKeyInformer.
	ApiKeies() ApiKeyInformer
	// ApiKeyBindings returns a ApiKeyBindingInformer.
	ApiKeyBindings() ApiKeyBindingInformer
	// ApiProxies returns a ApiProxyInformer.
	ApiProxies() ApiProxyInformer
	// MockTargets returns a MockTargetInformer.
	MockTargets() MockTargetInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// ApiKeies returns a ApiKeyInformer.
func (v *version) ApiKeies() ApiKeyInformer {
	return &apiKeyInformer{factory: v.SharedInformerFactory}
}

// ApiKeyBindings returns a ApiKeyBindingInformer.
func (v *version) ApiKeyBindings() ApiKeyBindingInformer {
	return &apiKeyBindingInformer{factory: v.SharedInformerFactory}
}

// ApiProxies returns a ApiProxyInformer.
func (v *version) ApiProxies() ApiProxyInformer {
	return &apiProxyInformer{factory: v.SharedInformerFactory}
}

// MockTargets returns a MockTargetInformer.
func (v *version) MockTargets() MockTargetInformer {
	return &mockTargetInformer{factory: v.SharedInformerFactory}
}
