// Code generated by protoc-gen-go. DO NOT EDIT.
// source: traffic.proto

/*
Package traffic is a generated protocol buffer package.

It is generated from these files:
	traffic.proto

It has these top-level messages:
	TrafficPoint
*/
package spec

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TrafficPoint struct {
	Time      int64  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	ProxyName string `protobuf:"bytes,3,opt,name=proxy_name,json=proxyName" json:"proxy_name,omitempty"`
	KeyName   string `protobuf:"bytes,4,opt,name=key_name,json=keyName" json:"key_name,omitempty"`
}

func (m *TrafficPoint) Reset()                    { *m = TrafficPoint{} }
func (m *TrafficPoint) String() string            { return proto.CompactTextString(m) }
func (*TrafficPoint) ProtoMessage()               {}
func (*TrafficPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TrafficPoint) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TrafficPoint) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TrafficPoint) GetProxyName() string {
	if m != nil {
		return m.ProxyName
	}
	return ""
}

func (m *TrafficPoint) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

func init() {
	proto.RegisterType((*TrafficPoint)(nil), "traffic.TrafficPoint")
}

func init() { proto.RegisterFile("traffic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x29, 0x4a, 0x4c,
	0x4b, 0xcb, 0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xaa, 0xb8,
	0x78, 0x42, 0x20, 0xcc, 0x80, 0xfc, 0xcc, 0xbc, 0x12, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xcc, 0xdc,
	0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x30, 0x5b, 0x48, 0x86, 0x8b, 0x33, 0x2f, 0x31,
	0x37, 0xb5, 0xb8, 0x20, 0x31, 0x39, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0x21, 0x20,
	0x24, 0xcb, 0xc5, 0x55, 0x50, 0x94, 0x5f, 0x51, 0x19, 0x0f, 0x12, 0x92, 0x60, 0x86, 0x48, 0x83,
	0x45, 0xfc, 0x12, 0x73, 0x53, 0x85, 0x24, 0xb9, 0x38, 0xb2, 0x53, 0xa1, 0x92, 0x2c, 0x60, 0x49,
	0xf6, 0xec, 0x54, 0xb0, 0x54, 0x12, 0x1b, 0xd8, 0x2d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x28, 0xe7, 0x4f, 0x52, 0x9c, 0x00, 0x00, 0x00,
}
