// Code generated by protoc-gen-go. DO NOT EDIT.

// Copyright (c) 2017 Northwestern Mutual.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
// source: traffic.proto

/*
Package spec is a generated protocol buffer package.

It is generated from these files:
	traffic.proto

It has these top-level messages:
	TrafficPoint
*/
package store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TrafficPoint struct {
	Time      int64  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	ProxyName string `protobuf:"bytes,3,opt,name=proxy_name,json=proxyName" json:"proxy_name,omitempty"`
	KeyName   string `protobuf:"bytes,4,opt,name=key_name,json=keyName" json:"key_name,omitempty"`
}

func (m *TrafficPoint) Reset()                    { *m = TrafficPoint{} }
func (m *TrafficPoint) String() string            { return proto.CompactTextString(m) }
func (*TrafficPoint) ProtoMessage()               {}
func (*TrafficPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TrafficPoint) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TrafficPoint) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TrafficPoint) GetProxyName() string {
	if m != nil {
		return m.ProxyName
	}
	return ""
}

func (m *TrafficPoint) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

func init() {
	proto.RegisterType((*TrafficPoint)(nil), "spec.TrafficPoint")
}

func init() { proto.RegisterFile("traffic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x29, 0x4a, 0x4c,
	0x4b, 0xcb, 0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x2e, 0x48, 0x4d, 0x56,
	0xaa, 0xe2, 0xe2, 0x09, 0x81, 0x08, 0x07, 0xe4, 0x67, 0xe6, 0x95, 0x08, 0x09, 0x71, 0xb1, 0x94,
	0x64, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x81, 0xd9, 0x42, 0x32, 0x5c, 0x9c,
	0x79, 0x89, 0xb9, 0xa9, 0xc5, 0x05, 0x89, 0xc9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x08, 0x01, 0x21, 0x59, 0x2e, 0xae, 0x82, 0xa2, 0xfc, 0x8a, 0xca, 0x78, 0x90, 0x90, 0x04, 0x33,
	0x44, 0x1a, 0x2c, 0xe2, 0x97, 0x98, 0x9b, 0x2a, 0x24, 0xc9, 0xc5, 0x91, 0x9d, 0x0a, 0x95, 0x64,
	0x01, 0x4b, 0xb2, 0x67, 0xa7, 0x82, 0xa5, 0x92, 0xd8, 0xc0, 0x0e, 0x31, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x6c, 0x5f, 0xec, 0x32, 0x99, 0x00, 0x00, 0x00,
}
